### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by rafabene** [raffaelespazzoli/openshift-enablement-exam#7]
Is the command: 

> ssh -o SendEnv=RHN_USERNAME -o SendEnv=RHN_PASSWORD -o SendEnv=DNS_DOMAIN -o SendEnv=RHN_SUB_POOL gcloud compute addresses list | grep ose-bastion | awk '{print $3}' cd openshift-enablement-exam

 meant to return a shell where I run the prepare-cluster.sh?

**Comment by raffaelespazzoli** [comment]
you `cd openshift-enablement-exam` and then run `prepare-cluster.sh`, when done run the ansible installer.

**Comment by rafabene** [comment]
The README formation lead me to think that `cd openshift-enablement-exam` was part of the ssh command. The PR https://github.com/raffaelespazzoli/openshift-enablement-exam/pull/3 fixes it
