### ISSUE TITLE
DNS Clarification

### ISSUE THREAD

**Issue by rafabene** [raffaelespazzoli/openshift-enablement-exam#8]
Do I need to have a valid DNS registered on ICANN?

**Comment by raffaelespazzoli** [comment]
I think the answer to this question is yes. You'll need to own a domain. I bought it from google (https://domains.google/). You also need to configure your domain to point to the google dns zone you define to resolve names. when you open the zone you'll see that there are 4 servers that look like:
```
ns-cloud-d1.googledomains.com.
ns-cloud-d2.googledomains.com.
ns-cloud-d3.googledomains.com.
ns-cloud-d4.googledomains.com.
```
you domain should point to all 4 to resolve names.

**Comment by rafabene** [comment]
Thanks
